name: effective-mobile-store

services:
  db:
    hostname: "${DB_HOSTNAME}"
    image: postgres:17.0-alpine3.20
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    expose:
      - "5432"

  nest:
    depends_on:
      - db
    environment:
      - DB_HOSTNAME=${DB_HOSTNAME}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:3000"
    volumes:
      - ./:/app

  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "81:80"
      
